# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          echo "unlinking python"
          brew unlink python
          echo "unlinking python3"
          brew unlink python3
          
          echo "installing python@3.9"
          brew install python@3.9
          
          export PATH=$PATH:/usr/local/opt/python@3.9/libexec/bin
          alias python=/usr/local/opt/python@3.9/libexec/bin/python
          alias pip=/usr/local/opt/python@3.9/libexec/bin/pip

          rm -f /usr/local/bin/python
          rm -f /usr/local/bin/pip
          sudo ln -s /usr/local/opt/python@3.9/libexec/bin/python /usr/local/bin/python
          sudo ln -s /usr/local/opt/python@3.9/libexec/bin/pip /usr/local/bin/pip

          which python
          which python3
          python --version
          python3 --version

          which pip
          which pip3

          pip install nose
